channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=5.24.1
  - jinja2 =2.11
  - networkx =2.5
  - matplotlib =3.3.4
  - graphviz =2.42
  - bcftools =1.12
  - samtools =1.12
  - bwa =0.7.17
  - pysam =0.16.0.1

